<?php


 function autoload_b82f125fdc89cf4d30dcee3051f90748($class)
{
    $classes = array(
        'Floream\BusinessLogicServices\SalesLogixService\SalesLogix' => __DIR__ .'/SalesLogix.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfKeyValueOfstringanyType' => __DIR__ .'/ArrayOfKeyValueOfstringanyType.php',
        'Floream\BusinessLogicServices\SalesLogixService\KeyValueOfstringanyType' => __DIR__ .'/KeyValueOfstringanyType.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateEntitiesValidateStudentRequest' => __DIR__ .'/ValidateEntitiesValidateStudentRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ServiceRequest' => __DIR__ .'/ServiceRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateEntitiesValidateStudentResponse' => __DIR__ .'/ValidateEntitiesValidateStudentResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ServiceResponse' => __DIR__ .'/ServiceResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfValidationMessage' => __DIR__ .'/ArrayOfValidationMessage.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidationMessage' => __DIR__ .'/ValidationMessage.php',
        'Floream\BusinessLogicServices\SalesLogixService\ResponseStatus' => __DIR__ .'/ResponseStatus.php',
        'Floream\BusinessLogicServices\SalesLogixService\Contact' => __DIR__ .'/Contact.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfAddress' => __DIR__ .'/ArrayOfAddress.php',
        'Floream\BusinessLogicServices\SalesLogixService\Address' => __DIR__ .'/Address.php',
        'Floream\BusinessLogicServices\SalesLogixService\Coordinates' => __DIR__ .'/Coordinates.php',
        'Floream\BusinessLogicServices\SalesLogixService\AddressType' => __DIR__ .'/AddressType.php',
        'Floream\BusinessLogicServices\SalesLogixService\ContactGender' => __DIR__ .'/ContactGender.php',
        'Floream\BusinessLogicServices\SalesLogixService\ContactTitle' => __DIR__ .'/ContactTitle.php',
        'Floream\BusinessLogicServices\SalesLogixService\ContactType' => __DIR__ .'/ContactType.php',
        'Floream\BusinessLogicServices\SalesLogixService\Course' => __DIR__ .'/Course.php',
        'Floream\BusinessLogicServices\SalesLogixService\Grade' => __DIR__ .'/Grade.php',
        'Floream\BusinessLogicServices\SalesLogixService\AccessRights' => __DIR__ .'/AccessRights.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamMembership' => __DIR__ .'/ExamMembership.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamVoucher' => __DIR__ .'/ExamVoucher.php',
        'Floream\BusinessLogicServices\SalesLogixService\Action' => __DIR__ .'/Action.php',
        'Floream\BusinessLogicServices\SalesLogixService\Opportunity' => __DIR__ .'/Opportunity.php',
        'Floream\BusinessLogicServices\SalesLogixService\AwardingBody' => __DIR__ .'/AwardingBody.php',
        'Floream\BusinessLogicServices\SalesLogixService\Communication' => __DIR__ .'/Communication.php',
        'Floream\BusinessLogicServices\SalesLogixService\WelcomeCall' => __DIR__ .'/WelcomeCall.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfProduct' => __DIR__ .'/ArrayOfProduct.php',
        'Floream\BusinessLogicServices\SalesLogixService\Product' => __DIR__ .'/Product.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateEntitiesValidateStudentOpportunityRequest' => __DIR__ .'/ValidateEntitiesValidateStudentOpportunityRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateEntitiesValidateTutorRequest' => __DIR__ .'/ValidateEntitiesValidateTutorRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateEntitiesValidateTutorResponse' => __DIR__ .'/ValidateEntitiesValidateTutorResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CryptographyEntitiesCryptographyRequest' => __DIR__ .'/CryptographyEntitiesCryptographyRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\CryptographyEntitiesCryptographyResponse' => __DIR__ .'/CryptographyEntitiesCryptographyResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CourseSoftwareEntitiesValidateSoftwareRequest' => __DIR__ .'/CourseSoftwareEntitiesValidateSoftwareRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\CourseSoftwareEntitiesSoftwareType' => __DIR__ .'/CourseSoftwareEntitiesSoftwareType.php',
        'Floream\BusinessLogicServices\SalesLogixService\CourseSoftwareEntitiesValidateSoftwareResponse' => __DIR__ .'/CourseSoftwareEntitiesValidateSoftwareResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CourseSoftwareEntitiesUpdateSoftwareRequest' => __DIR__ .'/CourseSoftwareEntitiesUpdateSoftwareRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\CourseSoftwareEntitiesUpdateSoftwareResponse' => __DIR__ .'/CourseSoftwareEntitiesUpdateSoftwareResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesGetExamsRequest' => __DIR__ .'/ExamEntitiesGetExamsRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesStatus' => __DIR__ .'/ExamEntitiesStatus.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesGetExamsResponse' => __DIR__ .'/ExamEntitiesGetExamsResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfExam' => __DIR__ .'/ArrayOfExam.php',
        'Floream\BusinessLogicServices\SalesLogixService\Exam' => __DIR__ .'/Exam.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfExamVenue' => __DIR__ .'/ArrayOfExamVenue.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamVenue' => __DIR__ .'/ExamVenue.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfExamVenueDate' => __DIR__ .'/ArrayOfExamVenueDate.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamVenueDate' => __DIR__ .'/ExamVenueDate.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamVenueBooking' => __DIR__ .'/ExamVenueBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\DateSpan' => __DIR__ .'/DateSpan.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamType' => __DIR__ .'/ExamType.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesExamBookingRequest' => __DIR__ .'/ExamEntitiesExamBookingRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfExamBooking' => __DIR__ .'/ArrayOfExamBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamBooking' => __DIR__ .'/ExamBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesExamBookingResponse' => __DIR__ .'/ExamEntitiesExamBookingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesCreateExamMembershipRequest' => __DIR__ .'/ExamEntitiesCreateExamMembershipRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamEntitiesCreateExamMembershipResponse' => __DIR__ .'/ExamEntitiesCreateExamMembershipResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\HistoryEntitiesGetHistoryRequest' => __DIR__ .'/HistoryEntitiesGetHistoryRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\PagingRequest' => __DIR__ .'/PagingRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\HistoryLevel' => __DIR__ .'/HistoryLevel.php',
        'Floream\BusinessLogicServices\SalesLogixService\HistoryEntitiesGetHistoryResponse' => __DIR__ .'/HistoryEntitiesGetHistoryResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\PagingResponse' => __DIR__ .'/PagingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfListItem' => __DIR__ .'/ArrayOfListItem.php',
        'Floream\BusinessLogicServices\SalesLogixService\ListItem' => __DIR__ .'/ListItem.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfHistory' => __DIR__ .'/ArrayOfHistory.php',
        'Floream\BusinessLogicServices\SalesLogixService\History' => __DIR__ .'/History.php',
        'Floream\BusinessLogicServices\SalesLogixService\HistoryEntitiesCreateHistoryRequest' => __DIR__ .'/HistoryEntitiesCreateHistoryRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\HistoryEntitiesCreateHistoryResponse' => __DIR__ .'/HistoryEntitiesCreateHistoryResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\TutorEntitiesGradeStudentRequest' => __DIR__ .'/TutorEntitiesGradeStudentRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\TutorEntitiesGradeStudentResponse' => __DIR__ .'/TutorEntitiesGradeStudentResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\SaveLeadEntitiesSaveLeadRequest' => __DIR__ .'/SaveLeadEntitiesSaveLeadRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\StoreRequest' => __DIR__ .'/StoreRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesCreateLeadRequest' => __DIR__ .'/CreateLeadEntitiesCreateLeadRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfContact' => __DIR__ .'/ArrayOfContact.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesLeadSource' => __DIR__ .'/CreateLeadEntitiesLeadSource.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesBrandAssociation' => __DIR__ .'/CreateLeadEntitiesBrandAssociation.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesSubmissionType' => __DIR__ .'/CreateLeadEntitiesSubmissionType.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesQuestions' => __DIR__ .'/CreateLeadEntitiesQuestions.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfAdditionalQuestion' => __DIR__ .'/ArrayOfAdditionalQuestion.php',
        'Floream\BusinessLogicServices\SalesLogixService\AdditionalQuestion' => __DIR__ .'/AdditionalQuestion.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesPlanToPay' => __DIR__ .'/CreateLeadEntitiesPlanToPay.php',
        'Floream\BusinessLogicServices\SalesLogixService\SaveLeadEntitiesSaveLeadResponse' => __DIR__ .'/SaveLeadEntitiesSaveLeadResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\StoreResponse' => __DIR__ .'/StoreResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesCreateLeadResponse' => __DIR__ .'/CreateLeadEntitiesCreateLeadResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadEntitiesIdentity' => __DIR__ .'/CreateLeadEntitiesIdentity.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfCreateLeadEntitiesIdentity' => __DIR__ .'/ArrayOfCreateLeadEntitiesIdentity.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSaleEntitiesCreateSaleRequest' => __DIR__ .'/CreateSaleEntitiesCreateSaleRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\PaymentPlan' => __DIR__ .'/PaymentPlan.php',
        'Floream\BusinessLogicServices\SalesLogixService\PaymentPlanMethod' => __DIR__ .'/PaymentPlanMethod.php',
        'Floream\BusinessLogicServices\SalesLogixService\Card' => __DIR__ .'/Card.php',
        'Floream\BusinessLogicServices\SalesLogixService\CardType' => __DIR__ .'/CardType.php',
        'Floream\BusinessLogicServices\SalesLogixService\CardDate' => __DIR__ .'/CardDate.php',
        'Floream\BusinessLogicServices\SalesLogixService\PaymentPlanType' => __DIR__ .'/PaymentPlanType.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSaleEntitiesCreateSaleResponse' => __DIR__ .'/CreateSaleEntitiesCreateSaleResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSaleEntitiesIdentity' => __DIR__ .'/CreateSaleEntitiesIdentity.php',
        'Floream\BusinessLogicServices\SalesLogixService\ProductEntitiesProductPricingRequest' => __DIR__ .'/ProductEntitiesProductPricingRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ProductEntitiesProductPricingResponse' => __DIR__ .'/ProductEntitiesProductPricingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfProductPricing' => __DIR__ .'/ArrayOfProductPricing.php',
        'Floream\BusinessLogicServices\SalesLogixService\ProductPricing' => __DIR__ .'/ProductPricing.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSaleEntitiesCreateAdhocPaymentRequest' => __DIR__ .'/CreateSaleEntitiesCreateAdhocPaymentRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\ArrayOfProductPaymentPlan' => __DIR__ .'/ArrayOfProductPaymentPlan.php',
        'Floream\BusinessLogicServices\SalesLogixService\ProductPaymentPlan' => __DIR__ .'/ProductPaymentPlan.php',
        'Floream\BusinessLogicServices\SalesLogixService\SonarScoreEntitiesSonarScoreRequest' => __DIR__ .'/SonarScoreEntitiesSonarScoreRequest.php',
        'Floream\BusinessLogicServices\SalesLogixService\SonarScoreEntitiesSonarScoreResponse' => __DIR__ .'/SonarScoreEntitiesSonarScoreResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ExamCentreEntitiesExamCentreResponse' => __DIR__ .'/ExamCentreEntitiesExamCentreResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateStudent' => __DIR__ .'/ValidateStudent.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateStudentResponse' => __DIR__ .'/ValidateStudentResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateStudentOpportunity' => __DIR__ .'/ValidateStudentOpportunity.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateStudentOpportunityResponse' => __DIR__ .'/ValidateStudentOpportunityResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateTutor' => __DIR__ .'/ValidateTutor.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateTutorResponse' => __DIR__ .'/ValidateTutorResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\Encrypt' => __DIR__ .'/Encrypt.php',
        'Floream\BusinessLogicServices\SalesLogixService\EncryptResponse' => __DIR__ .'/EncryptResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\Decrypt' => __DIR__ .'/Decrypt.php',
        'Floream\BusinessLogicServices\SalesLogixService\DecryptResponse' => __DIR__ .'/DecryptResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateSoftware' => __DIR__ .'/ValidateSoftware.php',
        'Floream\BusinessLogicServices\SalesLogixService\ValidateSoftwareResponse' => __DIR__ .'/ValidateSoftwareResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\UpdateSoftware' => __DIR__ .'/UpdateSoftware.php',
        'Floream\BusinessLogicServices\SalesLogixService\UpdateSoftwareResponse' => __DIR__ .'/UpdateSoftwareResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetExams' => __DIR__ .'/GetExams.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetExamsResponse' => __DIR__ .'/GetExamsResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateExamBooking' => __DIR__ .'/CreateExamBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateExamBookingResponse' => __DIR__ .'/CreateExamBookingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CancelExamBooking' => __DIR__ .'/CancelExamBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\CancelExamBookingResponse' => __DIR__ .'/CancelExamBookingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\RescheduleExamBooking' => __DIR__ .'/RescheduleExamBooking.php',
        'Floream\BusinessLogicServices\SalesLogixService\RescheduleExamBookingResponse' => __DIR__ .'/RescheduleExamBookingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateExamMembership' => __DIR__ .'/CreateExamMembership.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateExamMembershipResponse' => __DIR__ .'/CreateExamMembershipResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetHistoryNotes' => __DIR__ .'/GetHistoryNotes.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetHistoryNotesResponse' => __DIR__ .'/GetHistoryNotesResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateHistoryNote' => __DIR__ .'/CreateHistoryNote.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateHistoryNoteResponse' => __DIR__ .'/CreateHistoryNoteResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\GradeStudent' => __DIR__ .'/GradeStudent.php',
        'Floream\BusinessLogicServices\SalesLogixService\GradeStudentResponse' => __DIR__ .'/GradeStudentResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\SaveLead' => __DIR__ .'/SaveLead.php',
        'Floream\BusinessLogicServices\SalesLogixService\SaveLeadResponse' => __DIR__ .'/SaveLeadResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\GenerateUrl' => __DIR__ .'/GenerateUrl.php',
        'Floream\BusinessLogicServices\SalesLogixService\GenerateUrlResponse' => __DIR__ .'/GenerateUrlResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLead' => __DIR__ .'/CreateLead.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateLeadResponse' => __DIR__ .'/CreateLeadResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSale' => __DIR__ .'/CreateSale.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateSaleResponse' => __DIR__ .'/CreateSaleResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetPricing' => __DIR__ .'/GetPricing.php',
        'Floream\BusinessLogicServices\SalesLogixService\GetPricingResponse' => __DIR__ .'/GetPricingResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateAdhocPayment' => __DIR__ .'/CreateAdhocPayment.php',
        'Floream\BusinessLogicServices\SalesLogixService\CreateAdhocPaymentResponse' => __DIR__ .'/CreateAdhocPaymentResponse.php',
        'Floream\BusinessLogicServices\SalesLogixService\DoSonarScore' => __DIR__ .'/DoSonarScore.php',
        'Floream\BusinessLogicServices\SalesLogixService\DoSonarScoreResponse' => __DIR__ .'/DoSonarScoreResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_b82f125fdc89cf4d30dcee3051f90748');

// Do nothing. The rest is just leftovers from the code generation.
{
}
